language: java

jdk: oraclejdk8

os: linux

env:
   global:
      - PI_REPO=https://github.com/raspberrypi/tools
      - PI_LOCAL=target/opt/raspberrypi
      - PI_TOOLS=${PI_LOCAL}/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
      - MVN_TOOLCHAIN=https://repo1.maven.org/maven2/io/earcam/maven/io.earcam.maven.toolchain/2.0.1/io.earcam.maven.toolchain-2.0.1-linux-debian-amd64.xml

 
before_install:
   - sudo apt-get install mercurial
   - sudo apt-get install git
   - sudo apt-get install bc
   - sudo apt-get install maven
   - sudo apt-get install ant


install:  
   - mkdir -p ${PI_LOCAL}
   - (cd ${PI_LOCAL} && git clone ${PI_REPO})
   - ln -s ${PI_TOOLS}/bin/arm-linux-gnueabihf-gcc ${PI_TOOLS}/bin/gcc
   - ls -l ${PI_TOOLS}/bin
   - export PATH="${PI_TOOLS}:${PATH}"
   - wget ${MVN_TOOLCHAIN} -O ~/.m2/toolchains.xml
   - mvn -Dpi.tools=`pwd`/${PI_TOOLS} clean verify
    